### PR TITLE
Fix Taiwan Traditional Chinese String

### PR DESCRIPTION
**Pull request by jrthsr700tmax**
Replace the string from "設定快捷鍵" to "設定快速鍵".

#### What's this PR do?

- [x] Add new routes for user
- [x] Add instruction for using docker-compose

#### What are the relevant Git tickets?

// Put in link to Git Issue

#### Screenshots (if appropriate)

// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.

#### Any background context you want to provide? (if appropriate)

- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

### CODE REVIEW

**Comment by viettrungphan** [comment]
@p-z-l can you help me review this?

**Comment by p-z-l** [comment]
> @p-z-l can you help me review this?
<br>
Looks good as far as I can tell

**Comment by pan93412** [comment]
Let me check that.

**Review by pan93412 — APPROVED** [review]
It should be "快速鍵" indeed according to the glossary from Apple. Approved.

**Comment by viettrungphan** [comment]
Thanks @pan93412 @p-z-l

**Pull request merged**
