### PR TITLE
Add french (fr) localization

### PR DESCRIPTION
**Pull request by skeithtan**
#### What's this PR do?

- [x] Add french (fr) localization (it looks great!)
- [x] Move `showHowToUseAlwayHiddenPopover` tutorial text to `Localizable.strings` 

#### Screenshots

Capture d’écran 2021-04-07 à 19 54 31
Capture d’écran 2021-04-07 à 19 54 06
Capture d’écran 2021-04-07 à 19 54 01

### CODE REVIEW

**Comment by viettrungphan** [comment]
@skeithtan thanks for your contribution, we add a new tutorial for the "Alway hide" feature, can you help us to translate it?  You can rebase your current code to the latest "develop" branch. The PreferenceViewController line 296 and Mainstoryboard have new text need to translate.

**Comment by skeithtan** [comment]
Hi @viettrungphan, the pull request already includes the translation for the tutorial.

**Comment by viettrungphan** [comment]
@skeithtan help me translate this: "Use the full MenuBar on expanding" this is a new feature added for the next release. Just comment translate text here. Thanks.

**Comment by skeithtan** [comment]
> @skeithtan help me translate this: "Use the full MenuBar on expanding" this is a new feature added for the next release. Just comment translate text here. Thanks.

Here it is:

Utiliser toute la barre de menu lors du développement

**Pull request merged**
