### PR TITLE
Update zh-Hant Localization

### PR DESCRIPTION
**Pull request by pan93412**
#### What's this PR do?

- [x] Update zh-Hant localization
- [x] Help to update fr localization

#### What are the relevant Git tickets?

None

#### Screenshots (if appropriate)

截圖 2021-05-26 下午7 13 24
截圖 2021-05-26 下午7 15 50
截圖 2021-05-26 下午7 13 29
截圖 2021-05-26 下午7 14 34

### CODE REVIEW

**Comment by pan93412** [comment]
@viettrungphan "⭐️ Always Hidden" seems like not localized. could you check it for me? thanks! :-)

**Comment by viettrungphan** [comment]
That is a new part too, I don't see it in localizable.string file, don't forget "⭐️" char :), thank you again btw.

**Comment by pan93412** [comment]
> That is a new part too, I don't see it in localizable.string file, don't forget "⭐️" char :), thank you again btw.

I'm not sure what the new string ID is. could you help me confirm it? thanks! 😅

**Comment by viettrungphan** [comment]
I didn't translate anything before, not sure how it generated, try this: 
I open storyboard as sourcecode and see this
`<textFieldCell key="cell" lineBreakMode="clipping" title="⭐️Always Hidden" id="1jU-1x-cFf">
`I think "1jU-1x-cFf" is the id, try it and let me know.

**Comment by pan93412** [comment]
@viettrungphan fyi. could you take a look w/ this? thanks! ❤️ 

---

@skeithtan Could you help me translate a string that wasn't listed in your previous localization file? Thanks!
By the way, thanks for porting an untranslated string to all localization file :heart::smile:

**Comment by pan93412** [comment]
I've compiled a Release build for adc0d2c . You can copy it to `Applications` and launch it if you want to try the new version (would be better to build it by yourself / you may need to allow this in Gatekeeper).

[Hidden Bar.zip](https://github.com/dwarvesf/hidden/files/6548049/Hidden.Bar.zip)

**Comment by viettrungphan** [comment]
@pan93412 help me translate this: "Use the full MenuBar on expanding" this is a new feature added for the next release. Just comment translate text here. Thanks.

**Comment by pan93412** [comment]
> @pan93412 help me translate this: "Use the full MenuBar on expanding" this is a new feature added for the next release. Just comment translate text here. Thanks.

What will the feature do? Could I get some screencast about it?

**Comment by viettrungphan** [comment]
Screen Shot 2021-05-28 at 16 20 43
This related to #104

**Comment by viettrungphan** [comment]
Basically, we remove all app menu items on the left and make the app become first response. => lot of free space to show menus on the right

**Comment by pan93412** [comment]
> @pan93412 help me translate this: "Use the full MenuBar on expanding" this is a new feature added for the next release. Just comment translate text here. Thanks.

That is the feature I want very much! Here is the translation:

```
展開隱藏區時淨空選單列
```

I translated it by its meaning.

**Comment by viettrungphan** [comment]
Thanks

**Comment by viettrungphan** [comment]
Sorry but this is Chinese traditional? There is 2 versionss of Chinese in the app.

**Comment by pan93412** [comment]
> Sorry but this is Chinese traditional? There is 2 versionss of Chinese in the app.

Chinese (Traditional), zh-Hant. Thanks! By the way, could you help me internationalize this string?

截圖 2021-05-28 下午5 28 49

**Comment by viettrungphan** [comment]
What wrong, I use date formatter, It should render by system local.

**Comment by pan93412** [comment]
The order is wrong for non-English language. Maybe, it is because of the date formatting string?

**Comment by viettrungphan** [comment]
Date.dateString() + " " + Date.timeString() this

**Comment by pan93412** [comment]
> Date.dateString() + " " + Date.timeString() this

https://github.com/dwarvesf/hidden/blob/develop/hidden/Extensions/Date%2BExtension.swift#L14 Maybe here? The {date, time}String method seems like an extension. Try to make this string localizable?

**Comment by viettrungphan** [comment]
Good idea, let me push the latest code first.

**Comment by viettrungphan** [comment]
Please check out the latest develop branch.

**Pull request merged**
