### PR TITLE
Feature/ghost mode

### PR DESCRIPTION
**Pull request by viettrungphan**
#### What's this PR do?
- Add ghost mode
- Fix logic permanent
- Don't auto collapse when preference window opening.

### CODE REVIEW

**Comment by viettrungphan** [comment]
@p-z-l can you help me fix the UI of Ghost detail (?) screen

**Comment by p-z-l** [comment]
I'm not sure how to do that, pushing to this repo? Or your fork repo?

**Comment by viettrungphan** [comment]
This repo, just change the image with ghost icon instead of dot.

**Comment by viettrungphan** [comment]
We are make a survey and most of people don’t need this plus UI not friendly and we cannot  manage to move new or refreshed icons out of ghost area. The final decision was close this feature. 
However if you like this you can checkout and run this. Only tutorial image is missing.

**Comment by p-z-l** [comment]
Agreed, I can't think of any idea to keep it simple either..

**Comment by s-valent** [comment]
As I understand, the ghost feature was closed. Personally, I really enjoy this idea, so I made a version for myself. Here are the changes I made:
1. I remember when I first downloaded this app (by the way, it's amazing!), I tried to right click on arrow icon thinking the menu must be there. So I thought it would be logical to keep it there
2. I don't really rearrange icons in my menubar so often, so the separators just take place on the screen, doing nothing. I added a function to hide them when you don't need them.
3. So here comes the idea of the second separator that is used to always hide some icons (I use it for Spotlight as it cannot be hidden and everybody use it by shortcut). The separator always hides the icons after it when it's hidden, but you always can toggle it and rearrange as you wish. The problem of new refreshed icons isn't going anywhere, but at least you don't have to open menu each time.
4. For those, who don't like this concept, there is always an option to disable it (in fact, it is disabled by default to avoid confusion)

You can enjoy my work [here](https://github.com/s-valent/hidden-bar). Please remember, that it's just a suggestion how to improve the app, not obligatory. If you ask me, I think it feels natural in the way how the app could develop.

**Pull request closed without merging**
