### PR TITLE
UI improvement for Preferences Window

### PR DESCRIPTION
**Pull request by p-z-l**
#### UI improvement for Preferences Window

- [x] Slightly change the background color, with less saturation therefore text are more readable.
- [x] Fix the horrible display issue under light mode (happened at ae1d29fef83af0dc1e08c60f51d9f15ee3805129) by using dynamic window background color
- [x] A new banner picture
- [x] Changed title bar style for preferences window
- [x] Chinese Simplified language support

-----

Overall preview
> New banner picture ↓
New banner picture
> New title bar style ↓
New title bar style
> Chinese Simplified language support ↓
Screen Shot 2019-12-18 at 11 17 46 PM

### CODE REVIEW

**Comment by viettrungphan** [comment]
Wow, awesome

**Comment by p-z-l** [comment]
I'm wondering that should we really use a custom window background? Or just keep the macOS default one?

**Comment by p-z-l** [comment]
> Wow, awesome, we need record new video too

Ready for a new release?

**Comment by phucledien** [comment]
cool! thank you for the contribution. I think it's really eye-catching UI. And if you have time for making a video for the new release, it would be great!

**Comment by phucledien** [comment]
This PR solve the issue #25

**Comment by viettrungphan** [comment]
@p-z-l We can improve this better:
The way we put more banner images for each language will improve app size as well as make other people hard to help translate the app.
Suggestion change: 
- Remove Chinese banner image, 
- Make the original image without description text.
- Using 2 Labels on top of the banner image.
- Localize text base on language.
Benefits:
- Not increase app size when supporting more languages
- Easy to localize banner.

**Comment by viettrungphan** [comment]
@p-z-l We can improve this better:
The way we put more banner images for each language will improve app size as well as make other people hard to help translate the app.
Suggestion change:

Remove Chinese banner image,
Make the original image without description text (Hidden | Shown).
Using 2 Labels on top of the banner image.
Localize text base on language.
Benefits:
Not increase app size when supporting more languages
Easy to localize banner.
Related issue: #46

**Comment by p-z-l** [comment]
Working on this!

**Pull request merged**
