### PR TITLE
l10n(zh_TW): add localization of zh_TW

### PR DESCRIPTION
**Pull request by pan93412**
#### What's this PR do?
- [x] Add the translation for zh-Hant-TW

#### What are the relevant Git tickets?
None.

#### Screenshots (if appropriate)
General

<img width="281" alt="General > Time Interval" src="https://user-images.githubusercontent.com/28441561/109046567-d9f72680-770f-11eb-8868-557b06351314.png">

About
</div>

#### Any background context you want to provide? (if appropriate)
- Is there a blog post? **No**
- Does the knowledge base need an update? **No**
- Does this add new dependencies which need to be added to? **None**

### CODE REVIEW

**Comment by viettrungphan** [comment]
@p-z-l can you review this? Is this your native language? :)

**Comment by pan93412** [comment]
> @p-z-l can you review this? Is this your native language? :)

There are some difference between the simplified and the traditional chinese, for example, the vocabulary. But he may able to read these and give some common advices. :)

**Comment by p-z-l** [comment]
@viettrungphan
I can read traditional Chinese, but they uses a different translation scheme in Taiwan, which I know nothing about.

**Comment by p-z-l** [comment]
As far as I'm aware, everything in this PR is pretty good.

**Comment by viettrungphan** [comment]
@pan93412 we have a new feature for the newest version, can you help translate that part? Please checkout the latest develop brand and have a look at Localizable.string and MainStoryboard.

**Comment by pan93412** [comment]
> @pan93412 we have a new feature for the newest version, can you help translate that part? Please checkout the latest develop brand and have a look at Localizable.string and MainStoryboard.

thanks :) let me take a look with that

**Pull request merged**
