### PR TITLE
always hidden section, hide separators

### PR DESCRIPTION
**Pull request by s-valent**
*I'm really sorry for the inconvenience, still new to git & github and not doing very well. This pr is the updated copy of https://github.com/dwarvesf/hidden/pull/83 (I was gone and unable to update it).*

#### What's this PR do?

- [x] Allow hiding separator button ("|") to have more space in status bar
- [x] Optional "always hidden" section (can be turned on in menu)

#### What are the relevant Git tickets?

https://github.com/dwarvesf/hidden/issues/73
https://github.com/dwarvesf/hidden/issues/80

### CODE REVIEW

**Comment by Hybridx24** [comment]
@s-valent This is amazing! I hope the request is accepted, as this is a feature that has been sorely missing and can put this tweak above the competition

**Comment by phucledien** [comment]
Hi @s-valent, sorry for late response. I completely missed this 😢.

**Comment by Hybridx24** [comment]
@phucledien This is not mt request, but as I mentioned before it is a _crucial_ feature to any menu bar hiding app. I am forced to use Dozer for now, but would also love to switch to this app once this feature is implemented!

**Comment by phucledien** [comment]
Hi @s-valent, everything look good to me. But it would be nice if there is a way to guide user to use these new feature. But, as this has been long time now so I think I will merge and release this version. We will figure out the way to guide user later. 👍 

Thank you for the PR

**Review by phucledien — APPROVED** [review]

**Comment by s-valent** [comment]
@phucledien, no worries at all about late response, it's me who's late for 3 months. Thank you for your comment and ideas:)

I'll try to add some guidance

**Comment by phucledien** [comment]
cool @s-valent 👍

**Comment by qoomon** [comment]
Any timeline for the new release?

**Comment by s-valent** [comment]
> @s-valent Any timeline for the new release?

Hopefully I'll find some time to finish this week or the week after.

**Comment by Hybridx24** [comment]
@s-valent Any news on an update? Would love to be using this on Big Sur!

**Comment by rochakagrawal** [comment]
hi - any tips how to use the always hidden section bar for this app please?

@phucledien  @s-valent 

Is there a dev version i can use in the meantime if the release is not yet ready? I really need this always hide section bar and hate Dozer

thanks

**Pull request merged**
