### PR TITLE
Continuous Maintenance and Remastering

### PR DESCRIPTION
**Pull request by UeharaYou**
IMPORTANCE: This Pull Request is Re-posted since I updated the branch name in my repo. It is IDENTICAL to PR #260. 

What's this PR do?

Remastering Hidden Bar.

What's changed?

Re-arranged software architecture.
Completely rewrote StatusBarController for better consistency and stability, and improved code readability.
Rewrote LaunchAtLogin logic in adaptation to macOS 13.0.
Introduced LaunchAtLogin package dependency, and removed helper application.
Rewrote main toggle logic in Status Bar, allowing a more consistent way to interact.
Combining toggle function and context menu dropout into the main toggle button.
Introduced option-click and control-click for more versatile actions.
Simplified preference items.
Removed "show preference on launch" item. (Not necessary unless launch at the first time)
Removed "use always hidden" toggle. (You can just ignore it, adding this toggle increases code complexity)
What's next?

Improve localization.
Many localization might be unconfortable to read.
Quality-assured localization: English, Chinese-Simplified
Semi-assured localization: Chinese-Traditional, Japanese
Localization involving machine translation: all others
Remaster ui/ux.
Feature updates. (Public API only)
What's the motivation?

Hidden Bar has not been maintained for 2 years.
Some don't want to use paid software like Bartener.

### CODE REVIEW

**Comment by AlexanderWillner** [comment]
Just compiled your version. Nice work. However, it seems the setting window disappears after 5 seconds. You might also want to bump the version number.

**Comment by UeharaYou** [comment]
@AlexanderWillner Thanks for your encouragement ^_^. The setting window disappearing is mainly because the application switches back to "gadgets mode" and move the focus to other windows, if "Auto Collapse" feature is enabled. This is a minor issue as I will work on a fix shortly. I'm also working on new features like "monitoring item changes". Feel free to drop by and check them out.

**Comment by Aragamiz** [comment]
I have idea that if icon fresh, it show on in main zone.
other no activity icon hidden in bar. It can tune some rule to config it.

**Comment by UeharaYou** [comment]
@Aragamiz Currently looking for solutions for this feature. The public API apple provided is limited and i'm still looking for a workaround.

**Comment by bishshoy** [comment]
https://github.com/dwarvesf/hidden/discussions/264 possible to implement?

**Comment by SebastianMuskalla** [comment]
@UeharaYou the problem I have with your version is that after login, all icons are visible and the text "Invalid" appears next to the arrow. After clicking the arrow once, the text invalid disappears and the icons are still visible. After clicking it again, the icons get hidden. Would it be possible to fix that?

Thanks for your great work and for keeping this project alive!

**Comment by UeharaYou** [comment]
@bishshoy Yes it is possible to implement such feature with simple twitches. However, there might be potential risks of a software failure if such feature is implemented.

If not misunderstood, the feature request of #264 is described as "hiding all separators and the main toggle when folding up icons" and "the functionality of folding/expanding lays only on a keyboard shortcut for better look". It surely does better tidy up the status bar, but it also completely wiped out the possibility of "expanding the icons or opening the setting menu with the main toggle" by hiding it when folded. In this case, the keyboard shortcut is the only way to expand the icons or open the settings, which means if the keyboard shortcut failed (either accidentally unsetting it and closed the settings, or conflicted with shortcuts set from other applications), the software will be stuck at "folded" status, completely break down and can never function again (unless you find a way to manually reset all its settings laying who-know-where in your user library).

To give the status bar a better look, my solution is to hide the separators by default, only showing them when "Edit" mode is enabled to show you what sections the icons are in; while leaving the main toggle shown all the time, allowing user to access the settings when keyboard shortcuts have failed. I might also implement the ability of accessing the settings window via other reliable methods (such as by detecting user opening the application again) later, which then provides a more robust context to implement the full feature of #264. 

If you still have questions, or want a deeper conversation, feel free to comment again. Thank you.

**Comment by UeharaYou** [comment]
@SebastianMuskalla It seems to be a known issue of icon position detection, but more info necessary to confirm the cause. 

The logic in use might potentially fail when application starts up, mis-thinking the separators and toggles are in invalid positions. It can be confirmed by clicking the "Invalid" without dragging any icons in status bar, and simply being accepted ("Invalid" disappears). The cause might come from first time setup (unlikely), code-execution order (which have been explicitly addressed), uninitialized pointers (unlikely), or just the logic itself (not very well-tested, but works fine for me). Thus more information is necessary to determine which cause is in your case.

To address it, it is kind of you to answer some questions enlisted below:
1. If this issue persists? Or it just happened once, and had never happened again?
2. If issue persists, when will it occur? Every time re-opening the app regardless of logging in/out? Or just in every first time when opening the app after logging in (not happening when re-opening it until logging in next time)?
3. Is there a notch on your display? Are multiple displays in used?

It will be a pleasure to hear from you again. Thank you.

**Comment by bishshoy** [comment]
@UeharaYou It could be implemented as an alpha feature, and it can be kept as an alpha only feature until all possible bugs are eliminated. I am pretty sure that in a couple of minor and major revisions this won't be much of a problem. And by default, this feature would be turned off. Also when the user turns on this feature, he will be presented with a warning message that this particular feature is under development, so proceed with caution.

**Comment by UeharaYou** [comment]
@bishshoy This is plausible. A simple but full solution has already come to my head for this feature.

However I'm still a little bit concerned about this feature making into the stable branch after I finish it. This is because it is a less-intuitive way to use this software, which should not be activated most of the time. Also I need to come up with a way to better guard this feature, since a simple warning is not enough to stop a novice user from accidentally enabling it without reading the instructions.

So for now I will just implement feature #264 in "development" branch. For how or if I will merge it to the stable branch,I should come out with a better way, or a decision.

**Comment by SebastianMuskalla** [comment]
@UeharaYou Thanks for the quick reply!

The issue happens every time I start hidden bar (automatically after the login, but also when I manually quit and re-start the application.)
After I resolve it by clicking the arrow twice, the issue doesn't seem to occur again until I restart hidden bar.

I am using multiple displays, one of them (the internal screen) has a notch.

**Comment by MrSalta** [comment]
@UeharaYou I'm assuming nobody here has write access to merge this in, right?

**Comment by CaptainVincent** [comment]
I'm not sure if there are any volunteers willing to fork and maintain new features in the long term, similar to yt-dlp for youtube-dl.

**Comment by andrew-jolley** [comment]
Is it possible to download the v2.0-a1 version and use it?

**Comment by UeharaYou** [comment]
@SebastianMuskalla Sorry for late reply since a lot of other prioritized things in this month. Your display config is acknowledged, but I still cannot observe the replication of your issue (I used a third-party display on my Mac mini with an iPad as sidecar display, no displays with notches). I might try resolving this by reconsidering the start up procedure for now.

**Comment by UeharaYou** [comment]
@MrSalta No, unfortunately. Only the contributors have write access to this repo, currently none of who are active.

**Comment by SebastianMuskalla** [comment]
> @SebastianMuskalla Sorry for late reply since a lot of other prioritized things in this month. Your display config is acknowledged, but I still cannot observe the replication of your issue (I used a third-party display on my Mac mini with an iPad as sidecar display, no displays with notches). I might try resolving this by reconsidering the start up procedure for now.

No worries, thanks for the reply. I noticed that when I simply duplicate my internal display (with notch) to another display (without notch), the bug doesn't seem to occur. It just seems to happen when I use "extended" displays (no clue what the proper MacOS term for this is). Thanks for working on it. If I can somehow help you with additional information, please let me know.

**Comment by UeharaYou** [comment]
@CaptainVincent My work for now is to keep HiddenBar functional and stable, away from severe bugs or crashes. New features are for now pending (I have to get familiar with the macOS framework).

**Comment by UeharaYou** [comment]
@andrew-jolley There're no pre-built packages for v2.0 (signing issues). But you might build it from source. Please view the `ReadMe` in my branch [here](https://github.com/UeharaYou/HiddenBar/tree/stable) for build instructions.

**Comment by UeharaYou** [comment]
@SebastianMuskalla I found the issue for causing HiddenBar not properly handling position detection on startup.
A fix has been implemented for resolving this issue in v2.0.1(15).

For curiosity, here're details explaining how the issue is caused:
1. The status bar items are initiated with X-coordinate always at 0 relative to the main display, whom will be updated upon invoking the main RunLoop.
2. When multiple displays are in use, the origin point of the main display shifts in display arrangement plane, when there exist other displays at top/left of the main one.
3. The API returns X-coordinate from the display arrangement plane, which means it's not always 0 on startup.
4. The old logic assumes that the app is in startup stage (retries the position check after RunLoop is invoked) only when the API returns 0.

**Comment by phucledien** [comment]
Hey UeharaYou, thank you for your contribution. I have tried using it, and it works great. But tbh, we don't think that we need any more changes with the latest version of Hidden Bar. And we do not have many resources for maintaining the hidden bar.
You can consider to fork hidden bar, and keep continue developing new features on that.
Once again, thank you guys, and sorry for the late response.

**Comment by UeharaYou** [comment]
@phucledien Glad to have the respond. Very sorry to hear the sad news. Thank you and other members for creating such a great project.

\======
For all participants:
Due to the closure of this PR, for issues regarding my unofficial maintenance, please start/continue conversations in my repo [here](https://github.com/UeharaYou/HiddenBar/tree/stable). Issues of UM posted below this line will simply be ignored, thank you.
\======

**Comment by phucledien** [comment]
> @phucledien Glad to have the respond. Very sorry to hear the sad news. Thank you and other members for creating such a great project.

thank you for your understanding 🙏

**Pull request closed without merging**
