### PR TITLE
Continuous Maintenance and Remastering Pull Request

### PR DESCRIPTION
**Pull request by UeharaYou**
### What's this PR do?

Remastering Hidden Bar.

### What's changed?

1. Re-arranged software architecture.
2. Completely rewrote StatusBarController for better consistency and stability, and improved code readability.
3. Rewrote LaunchAtLogin logic in adaptation to macOS 13.0.
  - Introduced LaunchAtLogin package dependency, and removed helper application.
4. Rewrote main toggle logic in Status Bar, allowing a more consistent way to interact.
  - Combining toggle function and context menu dropout into the main toggle button.
  - Introduced option-click and control-click for more versatile actions.
5. Simplified preference items.
  - Removed "show preference on launch" item. (Not necessary unless launch at the first time)
  - Removed "use always hidden" toggle. (You can just ignore it, adding this toggle increases code complexity)

### What's next?

1. Improve localization.
  - Many localization might be unconfortable to read.
  - Verified localization: English, Chinese-Simplified
  - Semi-checked localization: Chinese-Traditional, Japanese
  - Localization involving machine translation: all others
2. Remaster ui/ux.
3. Feature updates. (Public API only)

### What's the motivation?

1. Hidden Bar has not been maintained for 2 years.
2. Some don't want to use paid software like Bartener.

### CODE REVIEW

**Comment by UeharaYou** [comment]
Relevant Issue: #259

**Comment by nitsujri** [comment]
@UeharaYou this looks incredible (admittedly, i have no idea about OSX development) and thanks so much for this.

Would it be possible to incorporate this feature request? https://github.com/dwarvesf/hidden/issues/228

This is such a massive pain for myself (I'm sure as others). I'm highly motivated to test/trial and provide feedback.

**Comment by UeharaYou** [comment]
@nitsujri Glad to hear that. 
To be honest I'm also novice to macOS development (I'm used to work with linux CLI applications mostly). It took me some time to  grep its logic and get to know which APIs it used, and rearrange it with my understandings. Since I still have to get familiar with cocoa and its APIs, and to prepare the environment for me to replicate and test the issues, it might take a while to get issues addressed.
As for Issue #228, does this issue still occurring with the rearranged version of Hidden Bar? I highly suspect that Apple has made some limitation to the status bar so that it won't get pass the notch. If true, an external area (like the Bartender) is necessary to avoid the limit, and Screen Recording and Accessibility APIs are essential to capture the icons from the original status bar. It might be complex to solve, but not impossible.

**Comment by nitsujri** [comment]
@UeharaYou how do I build this? I didn't see any build instructions.

Would it be possible to add a different `cask` and I could install+test directly?

[EDIT]
I expect the notch blocking icons is a hard OSX limitation which is why you need a separate menubar/external-area.

**Comment by UeharaYou** [comment]
@nitsujri 
Apologize for the inconvenience. I shall update the build instructions in README as soon as possible.

Currently there're no pre-build available for now. It's mainly because of worries about gatekeeper blocking my personal team cert as not trusted, and also that the software is still not well-tested and well-documented for a beta release. These might also risks for a brew cask rejection.

The way to test my version is to build it yourself, but it's fairly easy. Basically all you need to do is to import the project into Xcode (pull the whole project and open the .xcodeproj file), resolve the certificate error in target properties (you have to use your own cert to sign your own copies), then hit build icon (the "play" button) to build.

For how to navigate to update the cert, check the following screenshot:
Screenshot 2023-05-26 at 04 15 27

If you don't have a team cert, apply one by clicking "Add an Account" in the "Teams: " drop-list. 

My build environment is macOS 13.3.1 on M2 Mac mini, with Xcode 14.3.

**Comment by nitsujri** [comment]
@UeharaYou got it, i was able to successfully build after fighting through some "team errors".

As we suspect, the problem is still there:

WiFi_and_Bluetooth_and_UserSwitcher_and_Item-0

WiFi_and_Bluetooth_and_UserSwitcher_and_Item-0

On my laptop, it only goes up until dropbox then the notch is in the way, but on my 2nd monitor it goes much further.

A super minor bug seems to be all the fonts are in caps now?

Skitch_and_Postman

**Comment by UeharaYou** [comment]
@nitsujri 
So it seems like the notch is in deed a hard limit. There still should be a workaround for it.

But as for the ALL CAPED TEXT, it because I had "Localization Debugging" turned on, which will auto capitalize all text that's not included in the corresponding localization text file. This helps identifying unlocalized string, but this should not happen for English environment, as the localization file is missing. Although this is a slight issue as it can be resolved by just simply re-adding it back, since there might be some major changes to the UI, I would rather not fixing this issue for now. 

For temporary work-around, simply uncheck the "Show non-localized strings" checkbox in build scheme options. To edit scheme, select "Product > Scheme > Edit Scheme..." at the top-left Xcode menu.

Also it will be very kind of you to submit issues and PR inside the "UeharaYou:v2.0develop" branch in my unofficial repo. This helps organizing the workflow, and better tracing the development of the (unofficial) v2.0 alpha builds. I won't be able to handle issues and PR for this original repo until admitted by the original author as contributor, which might not be the case shortly, before that I could only manage my own unofficial repo.

**Pull request closed without merging**
