### PR TITLE
Updated App Icon to match MacOS 11-12

### PR DESCRIPTION
**Pull request by imabhaysutar**
#### What's this PR do?

- [x] Big Sur Style app icon
- [x] Updated Readme icon to reflect the same

#### Screenshots (if appropriate)

Hidden-512

### CODE REVIEW

**Comment by viettrungphan** [comment]
@imabhaysutar, thanks for your contribution. Do you check on both Dảk and light themes?

**Comment by imabhaysutar** [comment]
@viettrungphan I have. Does cheater-background.png need updating? or it is deprecated?

**Comment by imabhaysutar** [comment]
I have, tho the icon looks a bit rough on smaller sizes, will make a new commit for that in a bit.

**Comment by imabhaysutar** [comment]
@viettrungphan Tested with dark/light modes etc. I see no issues, attaching screenshots here.
Screenshot 2021-10-05 at 6 31 33 PM

Screenshot 2021-10-05 at 6 29 49 PM

**Comment by ghost** [comment]
Hi @imabhaysutar. The new icon looks great.  The current icon is one of the last ones left in my Applications folder that isn't Big Sur / Monterey friendly 😄.  

@viettrungphan When do you think this will make it as an update in the App Store?  Thanks for the great app!

**Comment by viettrungphan** [comment]
I have a bunch of updates and bugs fixed but I waiting for the official new macOS to test again.

**Comment by viettrungphan** [comment]
Screen Shot 2021-10-28 at 13 31 53
@imabhaysutar can you check AppIcon set again?

**Comment by imabhaysutar** [comment]
@viettrungphan Do i still have to check it? I see it is merged now.

edit- checking it

**Comment by viettrungphan** [comment]
You can fix it and push again or send me a large image file I will do it.

**Comment by imabhaysutar** [comment]
Hidden bar
Hope this is fine size, unfortunately i have lost the sketch file. Xcode is updating for me, hence the delay.

**Comment by viettrungphan** [comment]
Can you remove the outside shadow? Because we should use as app icon too, not only on About tab.

**Comment by imabhaysutar** [comment]
Hidden bar - no shadow
@viettrungphan here

**Comment by ya2s** [comment]
When will this be released?

**Comment by ghost** [comment]
@viettrungphan When are you expecting the next release to go out?

**Pull request merged**
